[package]
name = "pacman-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
find_folder = "0.3.0"
ndarray = "0.16.1"
piston_window = "0.130.0"
rand = "0.9.1"

